permalink: /:year/:month/:day/:title.html
paginate: 10
gems: [jekyll-paginate]
markdown: redcarpet

# 作者信息
author: 
  name: nbuxrr
  email: nbuxrr@gmail.com
  link: http://birdxu.com
  weibo: http://weibo.com/nbuxrr
  github: http://github.com/nbuxrr
  music: http://site.douban.com
  linkedin: https://www.linkedin.com

# 站点信息
title: xurr's blog
description: My personal blog
url: http://birdxu.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/gavatar.png
favicon: /public/img/favicon.png

# google analytics 设置
ga:
  id: UA-68721518-1
  url: birdxu.com

# disqus 设置
disqus:
  shortname: nbuxrr

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 


# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
